### ISSUE TITLE
add Code_Of_Conduct.md

### ISSUE THREAD

**Issue by Akshun-01** [samgrs/data-algorithms#2]
hey, this repo is missing Code_Of_Conduct.md, you can assign this task to me, I can do it for you

**Comment by samilagarrido** [comment]
please do it! thanks :)

**Comment by Akshun-01** [comment]
> please do it! thanks :)

Hey @samgrs , actually your the code of conduct file in your repo has content that is more suitable for the contributing.md file.
Should I change it ?
